imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ActeurBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    payment:
        currency: XOF
        decimal: false


framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

vich_uploader:
    db_driver: orm

    mappings:
        admin_images:
            uri_prefix: '%app.path.admin_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/admin/images/'

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: %locale%

    theme:
        simple: ~
        advanced:
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true
# Fos_user Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AdminBundle\Entity\User
#    profile:
#        form:
#            type: ActeurBundle\Form\Type\PorteurType
#    registration:
#        form:
#            type: ActeurBundle\Form\Type\PorteurType
#        confirmation:
#            enabled: true
#            template:   '@FOSUser/Registration/email.txt.twig'
   # profile:
    #    form:
     #       type: ScomBundle\Form\Type\ProfileFormType
    from_email:
        address: "infos@kaaloo.net"
        sender_name: "soutenir"
    service:
        user_manager: pugx_user_manager
    registration:
        confirmation:
            enabled: true
pugx_multi_user:
    users:
        user_one:
            entity:
                class: AdminBundle\Entity\Porteur
            registration:
                form:
                    type: ActeurBundle\Form\Type\PorteurType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: ActeurBundle:Registration:porteur_form.html.twig
            profile:
                form:
                    type: ActeurBundle\Form\Type\PorteurType
                    #name: fos_user_profile_form
                    validation_groups:  [Profile, Default]
        user_two:
            entity:
                class: AdminBundle\Entity\Donateurs
            registration:
                form:
                    type: ActeurBundle\Form\Type\DonateursType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: ActeurBundle:Registration:user_two.form.html.twig
            profile:
                form:
                    type: ActeurBundle\Form\Type\DonateursType



