<?php

namespace AdminBundle\Repository;
use Doctrine\ORM\Query;

/**
 * CodeValidationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeValidationRepository extends \Doctrine\ORM\EntityRepository
{
    public function VerifieCode($code){
        $sqb = $this->createQueryBuilder('c');
        $sqb
            ->select('c')
            ->where('c.codeInscription =:code')
            ->andWhere('c.utilise = false')
            ->setParameter('code',$code);
        // $qb->getQuery()->getOneOrNullResult(Query::HYDRATE_SINGLE_SCALAR);
        return $sqb->getQuery()->getScalarResult(Query::HYDRATE_SINGLE_SCALAR);

    }
}
