<?php

namespace AdminBundle\Repository;

/**
 * DonateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonateursRepository extends \Doctrine\ORM\EntityRepository
{
}
