<?php

namespace AdminBundle\Repository;

/**
 * moyen_paiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class moyen_paiementRepository extends \Doctrine\ORM\EntityRepository
{
}
