<?php

namespace AdminBundle\Repository;

/**
 * PorteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PorteurRepository extends \Doctrine\ORM\EntityRepository
{
}
