<?php

namespace AdminBundle\Repository;

/**
 * ProjetsValidesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsValidesRepository extends \Doctrine\ORM\EntityRepository
{
}
