<?php

namespace AdminBundle\Repository;

/**
 * ProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsRepository extends \Doctrine\ORM\EntityRepository
{
    public function projetsValides($limite){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.porteur','t')
          //  ->innerJoin('p.media','m')
            ->where('p.selectionne = true')
            ->orderBy('p.id','DESC')
            ->setMaxResults($limite);
           return $qb->getQuery()
            ->getResult();
    }

    public function tousLesProjetsValides(){
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.porteur','t')
            //  ->innerJoin('p.media','m')
            ->where('p.selectionne = true')
            ->orderBy('p.id','DESC');

        return $qb->getQuery()
            ->getResult();
    }
}
